version: "3.9"

services:

  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: practice-go-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${HOME}/.practice-go-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/.practice-go-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - dev-network

  sender:
    container_name: practice-go-sender
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: sender/Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - dev-network
    depends_on:
      - message-broker

  consumer:
    container_name: practice-go-consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - dev-network
    depends_on:
      - sender
      - message-broker

networks:
  dev-network:
    driver: bridge
    